version: '3.8'

services:
  web:
    build: .
    container_name: php-hello-world
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html:z
    restart: unless-stopped
    depends_on:
      - db
    environment:
      # Pass these variables from the host's .env to the container
      DB_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  db:
    image: docker.io/library/mariadb:latest
    container_name: mariadb-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  db_data: